Fix for bug 9327 (AttributeError: 'Symbol' object has no attribute 'split')
Now auto-resolving triage pending changes of "Inherit"


git-svn-id: http://svn.osafoundation.org/chandler/trunk@14449 3c49585b-f0f7-0310-b5f9-dfe92a88fbfe