Add a more-complex functional tests for reminders (especially on recurring events), and change reminders to make the test pass, r=jeffrey. (There are more complete notes about the specific changes in Bug 6551).
Fixes:
Bug 6551 (AttributeError: 'ReminderTimer' object has no attribute 'widget')
Bug 6752 (The reminder index can become out of order)
Bug 6865 (Trackback adding an alarm to a recurring event)
Bug 6997 (stack trace while adding note)
Bug 7016 (assertion: Creating an expired reminder that isn't marked 'keepExpired'?)
Bug 7125 (Talkback window when Chandler sitting idle, had to quit application)
and at least the assertion part of:
Bug 6864 (Lost an event)

git-svn-id: http://svn.osafoundation.org/chandler/trunk@12045 3c49585b-f0f7-0310-b5f9-dfe92a88fbfe